name: IG Publisher

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ig:
    name: Build Profiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"
      - name: Create temp dir and copy sushi project file
        run: mkdir temp && cp -v ${{ inputs.project-dir }}/sushi-config.yaml temp/
        shell: bash
      - name: Install sushi locally
        working-directory: temp
        run: npm install -g fsh-sushi
        shell: bash
      - name: Install Firely Terminal
        run: dotnet tool install -g firely.terminal
        shell: bash
      - name: Get dependencies
        working-directory: temp
        run: sushi
        shell: bash
      - name: Inflate FHIR packages
        run: fhir inflate-cache
        shell: bash
      - name: Remove temporary files
        run: npm remove -g fsh-sushi && rm -rf temp
        shell: bash
      - name: Build profiles
        uses: cybernop/build-fhir-ig@v1
        with:
          sushi-version: "3.0.0-beta.2"
      - name: Archive profile artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: output/package.tgz
      - name: Archive generated pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-ig
    if: github.ref_name == 'dev'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
