name: IG Publisher

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ig:
    name: Build Profiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"
      - name: Create temp dir and copy sushi project file
        run: mkdir temp && cp -v ./sushi-config.yaml temp/
        shell: bash
      - name: Install sushi locally
        working-directory: temp
        run: npm install -g fsh-sushi
        shell: bash
      - name: Install Firely Terminal
        run: dotnet tool install -g firely.terminal
        shell: bash
      - name: Get dependencies
        working-directory: temp
        run: sushi
        shell: bash
      - name: Inflate FHIR packages
        run: fhir inflate-cache
        shell: bash
      - name: Remove temporary files
        run: npm remove -g fsh-sushi && rm -rf temp
        shell: bash
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - run: npm install -g fsh-sushi@v3.12.1
        shell: bash
      - run: gem install jekyll
        shell: bash
      - run: sudo apt update && sudo apt install graphviz
        shell: bash
      - run: wget -q https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
        shell: bash
      - run: java -jar plantuml.jar -tsvg -o ../images input/images-source
        shell: bash
      - run: wget -q https://raw.githubusercontent.com/HL7/ig-publisher-scripts/main/_updatePublisher.sh && chmod a+x _updatePublisher.sh
        shell: bash
      - run: sed -n '133p' _updatePublisher.sh
        shell: bash
      - run: ./_updatePublisher.sh -y && chmod a+x _genonce.sh
        shell: bash
      - run: ./_genonce.sh
        shell: bash
      - name: Archive generated pages
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-ig
    if: github.ref_name == 'master'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
