name: FHIR Profiles

on:
  push:
    paths:
      - "**.fsh"
      - "**/sushi-config.yaml"
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-profiles:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: profiles
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"
      - name: Create temp dir and copy sushi project file
        run: mkdir temp && cp -v ./sushi-config.yaml temp/
        shell: bash
      - name: Install sushi locally
        working-directory: temp
        run: npm install -g fsh-sushi
        shell: bash
      - name: Install Firely Terminal
        run: dotnet tool install -g firely.terminal
        shell: bash
      - name: Get dependencies
        working-directory: temp
        run: sushi
        shell: bash
      - name: Inflate FHIR packages
        run: fhir inflate-cache
        shell: bash
      - name: Remove temporary files
        run: npm remove -g fsh-sushi && rm -rf temp
        shell: bash
      - name: Update FHIR Profiles
        uses: cybernop/build-fhir-profiles@v1
        with:
          sushi-version: "3.14.0"
          project-dir: profiles
      - name: Push built Profiles
        uses: cybernop/push-fsh-profiles@v1
        with:
          project-dir: profiles
